In [469]:
import numpy as np
import scipy.stats as st
import math
import matplotlib.pyplot as plt

In [470]:
plt.rcParams.update({'legend.fontsize': 30, 'axes.labelsize' : 30, 'axes.titlesize': 20})

Приступим к практическому внедрению метода градиентного спуска в жизнь (и в нашу задачу, в частности).

In [471]:
N = 10**3
TernConst = 1

Тут представлен тернарный поиск с количеством шагов $TernConst$.

In [472]:
def _ternarnik(x, y, func):
    m1 = x + (y - x) / 3
    m2 = y - (y - x) / 3
#     print("m1 = {}, m2 = {}".format(m1, m2))
#     print("func(m1) = {}, func(m2) = {}".format(func(m1), func(m2)))
    if func(m1) < func(m2):
#         print("x = {}, y = {}".format(m1, y))
        return (m1, y)
    else:
#         print("x = {}, y = {}".format(x, m2))
        return (x, m2)
def do_ternar(x, y, func):
    for i in range(TernConst):
        (x, y) = _ternarnik(x, y, func)
    return (x, y)

Эта операция служит для получения случайных значений массивов $p$ и $\pi$. Получившиеся значения $p \in [0, 2]$.

In [473]:
def make_random(n):
    P_base = list(np.random.rand(n - 1))
    P_base.append(0)
    P_base.append(1)
    P_base.sort()
    P = np.array([P_base[i] - P_base[i - 1] for i in range(1, n + 1)])
    P = np.floor(P * 100) / 100
    P[0] += 1 - np.sum(P)
    p = np.floor(np.random.rand(n, n) * 2 * 100) / 100
    #p = (np.random.rand(n, n) - np.ones((n, n)) / 2) * 2
    return [P, p]

Здесь описаны функции получения значений $F$ и $\nabla F$ (по уже полученной формуле и беря проекцию под конец).

In [474]:
def base_func(P, p, x):
    x = np.array(x)
    p = np.array(p)
    result = 0
    for (Pi, pi) in zip (P, p):
#         print(Pi)
#         print(x)
#         print(pi)
#         print(pi @ x)
        result += Pi * math.log(pi @ x)
    return result
def base_grad(P, p, x):
    n = len(x)
    x = np.array(x)
    p = np.array(p)
    result = np.zeros(n)
    for (Pi, pi, p_j) in zip (P, p, p.transpose()):
        result += pi * (Pi / (pi @ x))
#     print(result)
    result -= np.ones((n)) * ((np.ones((n)) @ result) / n)
    return result

In [475]:
def make_func(P, p):
    return lambda x: base_func(P, p, x)
def make_grad(P, p):
    return lambda x: base_grad(P, p, x)

Следующая точка градиентного поиска получается из этих функций. Первую из них, с заданным шагом, мы пока не используем. Во второй, мы сначала вычисляем предельную точку множества по направлению градиента (которая выйдет за $x \succeq 0$). А затем отправляем $x_{i - 1}$ и $x_{пред}$ на тернарный поиск и возвращаем среднее от результата.

In [476]:
def next_grad_point_with_step(x_prev, lambd, grad):
    return(x_prev + lambd * grad(x_prev))
def next_grad_point(x_prev, grad, func):
    grad = grad(x_prev)
#     print(grad)
    t = None
    for (x, g) in zip(x_prev, grad):
        comp = None
        if g < 0:
            comp = -x / g
#         print('x = {}, grad = {}, t = {}'.format(x, g, comp))
            if (t == None) or comp < t:
                t = comp
#     print(x_prev + t * 98 / 100 * grad)
    points = do_ternar(x_prev, x_prev + t * 98 / 100 * grad, func)
    return((points[0] + points[1]) / 2)

Конфиг наших экспериментов. Состоит из задаваемой части и случайной, в которой мы только задаем размерность.

In [477]:
config_base = [
    {
        'P': [0.5, 0.5],
        'p': [[1, 1], [1, 1]], 
        'lambda': 1,
        'Graphs': []
    },
    {
        'P': [0.5, 0.5],
        'p': [[1, 20], [1, 1]],
        'lambda': 1,
        'Graphs': []
    },
    {
        'P': [0.5, 0.5],
        'p': [[19, 20], [1, 1]], 
        'lambda': 1,
        'Graphs': []
    },
    {
        'P': [0.1, 0.9],
        'p': [[19, 1], [20, 1]], 
        'lambda': 1,
        'Graphs': []
    }
]
random_config = [3, 3, 3, 4, 4, 4, 4, 6, 6, 6, 10, 10, 20]

In [478]:
data = config_base.copy()
for k in random_config:
    ran = make_random(k)
    data.append({
        'P': ran[0],
        'p': ran[1],
        'lambda': 1,
        'Graphs': []
    })

Следующии три окошка представляют из себя три серии экспериментов, с различным выбором начальных точек:
  * $x_0 = (\frac{1}{n}, \frac{1}{n},..., \frac{1}{n})$
  * $x_0 = (1, 0,..., 0)$
  * $x_0 = (\frac{1}{2}, \frac{1}{2}, 0,..., 0)$
  Каждая серия заканчивается либо при уменьшении нормы градиента или нормы разности $x_i - x_{i - 1}$ ниже определенного значения, либо по достижении предельного количества шагов.

In [479]:
for data_map in data:
    P = data_map['P']
    p = data_map['p']
    lambd = data_map['lambda'] / 10
    func = make_func(P, p)
    grad = make_grad(P, p)
    x0 = np.ones((len(P))) / len(P)
    values = [func(x0)]
    Xs = [x0]
    data_map['Graphs'].append({
        'x0': x0,
        'values': values,
        'Xs': Xs
    })
    print(data_map)
    for i in range(N):
#         print("Grad: {}".format(grad(Xs[-1])))
        if np.linalg.norm(grad(Xs[-1])) < 0.01:
            print("Check! Grad\n")
            break
        Xs.append(next_grad_point(Xs[-1], grad, func))
#         print("Next x: {}".format(Xs[-1]))
        values.append(func(Xs[-1]))
        if (np.linalg.norm(Xs[-1] - Xs[-2]) < 10**-4):
            print("Check! Norm\n")
            break
    if i == N - 1:
        print("Check! Ammount")

{'P': [0.5, 0.5], 'p': [[1, 1], [1, 1]], 'lambda': 1, 'Graphs': [{'x0': array([0.5, 0.5]), 'values': [0.0], 'Xs': [array([0.5, 0.5])]}]}
Check! Grad

{'P': [0.5, 0.5], 'p': [[1, 20], [1, 1]], 'lambda': 1, 'Graphs': [{'x0': array([0.5, 0.5]), 'values': [1.1756876285817388], 'Xs': [array([0.5, 0.5])]}]}
Check! Norm

{'P': [0.5, 0.5], 'p': [[19, 20], [1, 1]], 'lambda': 1, 'Graphs': [{'x0': array([0.5, 0.5]), 'values': [1.4852072327848505], 'Xs': [array([0.5, 0.5])]}]}
Check! Norm

{'P': [0.1, 0.9], 'p': [[19, 1], [20, 1]], 'lambda': 1, 'Graphs': [{'x0': array([0.5, 0.5]), 'values': [2.3464962407465344], 'Xs': [array([0.5, 0.5])]}]}
Check! Norm

{'P': array([0.74, 0.14, 0.12]), 'p': array([[1.01, 1.06, 0.77],
       [0.  , 0.7 , 1.86],
       [0.19, 1.47, 1.  ]]), 'lambda': 1, 'Graphs': [{'x0': array([0.33333333, 0.33333333, 0.33333333]), 'values': [-0.07719713913596604], 'Xs': [array([0.33333333, 0.33333333, 0.33333333])]}]}
Check! Norm

{'P': array([0.75, 0.21, 0.04]), 'p': array([[0.55,

In [480]:
for data_map in data:
    P = data_map['P']
    p = data_map['p']
    lambd = data_map['lambda'] / 10
    func = make_func(P, p)
    grad = make_grad(P, p) 
    x0 = np.zeros(len(P))
    x0[0] = 0.99
    x0[1] = 0.01
    values = [func(x0)]
    Xs = [x0]
    data_map['Graphs'].append({
        'x0': x0,
        'values': values,
        'Xs': Xs
    })
    print(data_map)
    for i in range(N):
#         print("Grad: {}".format(grad(Xs[-1])))
        if np.linalg.norm(grad(Xs[-1])) < 0.01:
            print("Check! Grad\n")
            break
        Xs.append(next_grad_point(Xs[-1], grad, func))
#         print("Next x: {}".format(Xs[-1]))
        values.append(func(Xs[-1]))
        if (np.linalg.norm(Xs[-1] - Xs[-2]) < 10**-4):
            print("Check! Norm\n")
            break
    if i == N - 1:
        print("Check! Ammount")

{'P': [0.5, 0.5], 'p': [[1, 1], [1, 1]], 'lambda': 1, 'Graphs': [{'x0': array([0.5, 0.5]), 'values': [0.0], 'Xs': [array([0.5, 0.5])]}, {'x0': array([0.99, 0.01]), 'values': [0.0], 'Xs': [array([0.99, 0.01])]}]}
Check! Grad

{'P': [0.5, 0.5], 'p': [[1, 20], [1, 1]], 'lambda': 1, 'Graphs': [{'x0': array([0.5, 0.5]), 'values': [1.1756876285817388, 1.407903920679879, 1.4684768622370055, 1.4878722847883117, 1.4944241759814736, 1.4966756050444372, 1.497453740049126, 1.4977232110939578, 1.4978165938333992, 1.4978489624457942], 'Xs': [array([0.5, 0.5]), array([0.17333333, 0.82666667]), array([0.06008889, 0.93991111]), array([0.02083081, 0.97916919]), array([0.00722135, 0.99277865]), array([0.0025034, 0.9974966]), array([8.67845692e-04, 9.99132154e-01]), array([3.00853173e-04, 9.99699147e-01]), array([1.04295767e-04, 9.99895704e-01]), array([3.61558658e-05, 9.99963844e-01])]}, {'x0': array([0.99, 0.01]), 'values': [0.08697665356171899], 'Xs': [array([0.99, 0.01])]}]}
Check! Norm

{'P': [0.5, 0

In [481]:
for data_map in data:
    P = data_map['P']
    p = data_map['p']
    lambd = data_map['lambda'] / 10
    func = make_func(P, p)
    grad = make_grad(P, p) 
    x0 = np.zeros(len(P))
    x0[0] = 0.5
    x0[1] = 0.5
    values = [func(x0)]
    Xs = [x0]
    data_map['Graphs'].append({
        'x0': x0,
        'values': values,
        'Xs': Xs
    })
    print(data_map)
    for i in range(N):
#         print("Grad: {}".format(grad(Xs[-1])))
        if np.linalg.norm(grad(Xs[-1])) < 0.01:
            print("Check! Grad\n")
            break
        Xs.append(next_grad_point(Xs[-1], grad, func))
#         print("Next x: {}".format(Xs[-1]))
        values.append(func(Xs[-1]))
        if (np.linalg.norm(Xs[-1] - Xs[-2]) < 10**-4):
            print("Check! Norm\n")
            break
    if i == N - 1:
        print("Check! Ammount")

{'P': [0.5, 0.5], 'p': [[1, 1], [1, 1]], 'lambda': 1, 'Graphs': [{'x0': array([0.5, 0.5]), 'values': [0.0], 'Xs': [array([0.5, 0.5])]}, {'x0': array([0.99, 0.01]), 'values': [0.0], 'Xs': [array([0.99, 0.01])]}, {'x0': array([0.5, 0.5]), 'values': [0.0], 'Xs': [array([0.5, 0.5])]}]}
Check! Grad

{'P': [0.5, 0.5], 'p': [[1, 20], [1, 1]], 'lambda': 1, 'Graphs': [{'x0': array([0.5, 0.5]), 'values': [1.1756876285817388, 1.407903920679879, 1.4684768622370055, 1.4878722847883117, 1.4944241759814736, 1.4966756050444372, 1.497453740049126, 1.4977232110939578, 1.4978165938333992, 1.4978489624457942], 'Xs': [array([0.5, 0.5]), array([0.17333333, 0.82666667]), array([0.06008889, 0.93991111]), array([0.02083081, 0.97916919]), array([0.00722135, 0.99277865]), array([0.0025034, 0.9974966]), array([8.67845692e-04, 9.99132154e-01]), array([3.00853173e-04, 9.99699147e-01]), array([1.04295767e-04, 9.99895704e-01]), array([3.61558658e-05, 9.99963844e-01])]}, {'x0': array([0.99, 0.01]), 'values': [0.086976

       [0.04, 1.98, 0.51]]), 'lambda': 1, 'Graphs': [{'x0': array([0.33333333, 0.33333333, 0.33333333]), 'values': [0.11394867227056907, 0.2844532245021647, 0.3376246536060906, 0.35543656889692643, 0.3615401431765049, 0.36364762428379943, 0.3643772108049726, 0.3646300133507016, 0.3647176370608076, 0.36474801153743863], 'Xs': [array([0.33333333, 0.33333333, 0.33333333]), array([0.11555556, 0.39717068, 0.48727377]), array([0.04005926, 0.41731305, 0.54262769]), array([0.01388721, 0.42414928, 0.56196351]), array([0.00481423, 0.42650388, 0.56868188]), array([0.00166893, 0.42731839, 0.57101268]), array([0.00057856, 0.42760054, 0.57182089]), array([2.00568782e-04, 4.27698334e-01, 5.72101098e-01]), array([6.95305111e-05, 4.27732231e-01, 5.72198239e-01]), array([2.41039105e-05, 4.27743981e-01, 5.72231915e-01])]}, {'x0': array([0.99, 0.01, 0.  ]), 'values': [-0.9142372714672652, -0.9142372714672652], 'Xs': [array([0.99, 0.01, 0.  ]), array([0.99, 0.01, 0.  ])]}, {'x0': array([0.5, 0.5, 0. ]), 'v

Наконец, сравнительные графики для каждого набора $p$ и $\pi$ для всех трех серий

In [482]:
rows_per_data = 2 + (len(data[0]['Graphs']) // 3 + 1) * 2 + 1
gridsize = (len(data) * rows_per_data, 3)
fig = plt.figure(figsize=(40, 40 * len(data)), facecolor=matplotlib.colors.get_named_colors_mapping()['xkcd:cream'])
plt.subplots_adjust(hspace=0.8)
for i in range(len(data)):
    data_map = data[i]
    P = data_map['P']
    p = data_map['p']
    labels = ['$x_{' + '{}'.format(i + 1) + '}$' for i in range(len(P))]
    ax0 = plt.subplot2grid(gridsize, (i * rows_per_data, 0), colspan=3, rowspan=2)
    for (Pi, pi) in zip(P, p):
        params += r'$\pi$: {:.2f}, $p_j$: {}'.format(Pi, pi) + '\n'
    ax0.set_title(params, {'fontsize': 30}, loc='left')
    ax0.set_xlabel(r'$k$')
    ax0.set_ylabel(r'$F(x_k)$')
    graphs = data_map['Graphs']
    for j in range(len(gaphs)):
        graph = graphs[j]
        Xs = np.array(graph['Xs'])
        x0 = graph['x0']
        n = len(Xs)
        graph_x = range(n)
        ax0.plot(graph_x, graph['values'], label='$x_0 = ${}'.format(np.floor(x0*100) / 100))
        axi = plt.subplot2grid(gridsize, (i * rows_per_data + (j // 3) * 2 + 2, j % 3), colspan=1, rowspan=2)
        params = ''
        axi.stackplot(graph_x, *[Xs[:, i] for i in range(len(P))], labels=labels)
        axi.legend()
        axi.set_title('$x_0 = ${}'.format(np.floor(x0*100) / 100))
        axi.set_xlabel(r'$k$')
        axi.set_ylabel(r'$X$')
    ax0.legend()

In [483]:
import pprint
pprint.pprint(data)

[{'Graphs': [{'Xs': [array([0.5, 0.5])],
              'values': [0.0],
              'x0': array([0.5, 0.5])},
             {'Xs': [array([0.99, 0.01])],
              'values': [0.0],
              'x0': array([0.99, 0.01])},
             {'Xs': [array([0.5, 0.5])],
              'values': [0.0],
              'x0': array([0.5, 0.5])}],
  'P': [0.5, 0.5],
  'lambda': 1,
  'p': [[1, 1], [1, 1]]},
 {'Graphs': [{'Xs': [array([0.5, 0.5]),
                     array([0.17333333, 0.82666667]),
                     array([0.06008889, 0.93991111]),
                     array([0.02083081, 0.97916919]),
                     array([0.00722135, 0.99277865]),
                     array([0.0025034, 0.9974966]),
                     array([8.67845692e-04, 9.99132154e-01]),
                     array([3.00853173e-04, 9.99699147e-01]),
                     array([1.04295767e-04, 9.99895704e-01]),
                     array([3.61558658e-05, 9.99963844e-01])],
              'values': [1.175687628581738

       0.16666667]),
                     array([0.08870256, 0.40221492, 0.05777778, 0.2931914 , 0.09423265,
       0.0638807 ]),
                     array([0.07428901, 0.46526111, 0.02002963, 0.3269743 , 0.06796714,
       0.04547881]),
                     array([0.0693565 , 0.48686316, 0.0069436 , 0.33836197, 0.05939915,
       0.03907562]),
                     array([0.06765416, 0.49431576, 0.00240712, 0.34226975, 0.0564983 ,
       0.03685491]),
                     array([0.06706493, 0.49689478, 0.00083447, 0.3436196 , 0.0555012 ,
       0.03608502]),
                     array([6.68607684e-02, 4.97788283e-01, 2.89281897e-04, 3.44086965e-01,
       5.51565782e-02, 3.58181226e-02]),
                     array([6.67900062e-02, 4.98097964e-01, 1.00284391e-04, 3.44248915e-01,
       5.50372324e-02, 3.57255978e-02]),
                     array([6.67654769e-02, 4.98205312e-01, 3.47652556e-05, 3.44305049e-01,
       5.49958741e-02, 3.56935225e-02]),
                     array([6.67569